title: Glacier Protocol
description: Glacier Protocol is a secure cold storage protocol for bitcoin
show_downloads: true
google_analytics:

name: squarebox
rouge: true
excerpt_separator: <!--more-->
paginate: 3
paginate_path: "blog/page:num"
    
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
