
description: Glacier is a protocol for secure cold storage of bitcoins.
show_downloads: true
google_analytics:

name: Glacier Protocol
rouge: true
excerpt_separator: <!--more-->
paginate: 3
paginate_path: "blog/page:num"
    
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME


# GitHub Pages is sometimes substituting in http://glacierprotocol.org for {{site.url}}, which results
# in a garbled page due to browsers' security rules about mixed content (https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content)
#
# so we hardcode in this URL here.
# 
# jekyll automatically swaps this out for localhost:4000 in development environments (i.e. when
# JEKYLL_ENV is set to its default of "development").

url: https://glacierprotocol.org
