theme: jekyll-theme-cayman

title: Glacier Protocol
description: Glacier Protocol is a secure cold storage protocol for bitcoin
show_downloads: true
google_analytics:

title: Glacier Protocol

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME